/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mock from "./mock";
export type { mock };
import type * as v1 from "./v1";
export type { v1 };
import type * as v2 from "./v2";
export type { v2 };
