/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iStakingSol from "./IStaking.sol";
export { IBridge__factory } from "./IBridge__factory";
export { IERC20Mintable__factory } from "./IERC20Mintable__factory";
export { IOwnablePausable__factory } from "./IOwnablePausable__factory";
export { IStakeManager__factory } from "./IStakeManager__factory";
