/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStakingPrecompile,
  IStakingPrecompileInterface,
} from "../../../../contracts/interfaces/IStaking.sol/IStakingPrecompile";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "hotkey",
        type: "bytes32",
      },
      {
        internalType: "uint16",
        name: "netUid",
        type: "uint16",
      },
    ],
    name: "addStake",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "hotkey",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint16",
        name: "netUid",
        type: "uint16",
      },
    ],
    name: "removeStake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IStakingPrecompile__factory {
  static readonly abi = _abi;
  static createInterface(): IStakingPrecompileInterface {
    return new Interface(_abi) as IStakingPrecompileInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IStakingPrecompile {
    return new Contract(address, _abi, runner) as unknown as IStakingPrecompile;
  }
}
