/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IBridge {
  export type TokenInfoStruct = {
    tokenAddress: AddressLike;
    managed: boolean;
    enabled: boolean;
    supported: boolean;
  };

  export type TokenInfoStructOutput = [
    tokenAddress: string,
    managed: boolean,
    enabled: boolean,
    supported: boolean
  ] & {
    tokenAddress: string;
    managed: boolean;
    enabled: boolean;
    supported: boolean;
  };

  export type TokenMetadataStruct = {
    name: string;
    symbol: string;
    decimals: BigNumberish;
  };

  export type TokenMetadataStructOutput = [
    name: string,
    symbol: string,
    decimals: bigint
  ] & { name: string; symbol: string; decimals: bigint };

  export type TransferRequestStruct = {
    nonce: BigNumberish;
    from: AddressLike;
    to: AddressLike;
    tokenKey: BytesLike;
    amount: BigNumberish;
    srcChainId: BigNumberish;
    destChainId: BigNumberish;
  };

  export type TransferRequestStructOutput = [
    nonce: bigint,
    from: string,
    to: string,
    tokenKey: string,
    amount: bigint,
    srcChainId: bigint,
    destChainId: bigint
  ] & {
    nonce: bigint;
    from: string;
    to: string;
    tokenKey: string;
    amount: bigint;
    srcChainId: bigint;
    destChainId: bigint;
  };

  export type TransferExecutionDetailsStruct = {
    to: AddressLike;
    amount: BigNumberish;
    nonce: BigNumberish;
    tokenKey: BytesLike;
    srcChainId: BigNumberish;
    tokenMetadata: IBridge.TokenMetadataStruct;
  };

  export type TransferExecutionDetailsStructOutput = [
    to: string,
    amount: bigint,
    nonce: bigint,
    tokenKey: string,
    srcChainId: bigint,
    tokenMetadata: IBridge.TokenMetadataStructOutput
  ] & {
    to: string;
    amount: bigint;
    nonce: bigint;
    tokenKey: string;
    srcChainId: bigint;
    tokenMetadata: IBridge.TokenMetadataStructOutput;
  };
}

export interface IBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "executeTransferRequests"
      | "getAdmin"
      | "getAuthority"
      | "requestTransfer"
      | "setStakingManager"
      | "updateWhitelistStatus"
      | "whitelistToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "NewTokenWhitelisted"
      | "TokenWhitelistStatusUpdated"
      | "TokenWrapped"
      | "TransferRequestExecuted"
      | "TransferRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "executeTransferRequests",
    values: [IBridge.TransferExecutionDetailsStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "getAdmin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAuthority",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestTransfer",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakingManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWhitelistStatus",
    values: [BytesLike, boolean, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistToken",
    values: [BytesLike, boolean, AddressLike, string, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeTransferRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakingManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWhitelistStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistToken",
    data: BytesLike
  ): Result;
}

export namespace NewTokenWhitelistedEvent {
  export type InputTuple = [
    tokenKey: BytesLike,
    tokenInfo: IBridge.TokenInfoStruct,
    tokenMetadata: IBridge.TokenMetadataStruct
  ];
  export type OutputTuple = [
    tokenKey: string,
    tokenInfo: IBridge.TokenInfoStructOutput,
    tokenMetadata: IBridge.TokenMetadataStructOutput
  ];
  export interface OutputObject {
    tokenKey: string;
    tokenInfo: IBridge.TokenInfoStructOutput;
    tokenMetadata: IBridge.TokenMetadataStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenWhitelistStatusUpdatedEvent {
  export type InputTuple = [
    tokenKey: BytesLike,
    tokenInfo: IBridge.TokenInfoStruct
  ];
  export type OutputTuple = [
    tokenKey: string,
    tokenInfo: IBridge.TokenInfoStructOutput
  ];
  export interface OutputObject {
    tokenKey: string;
    tokenInfo: IBridge.TokenInfoStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenWrappedEvent {
  export type InputTuple = [
    tokenKey: BytesLike,
    wrappedToken: AddressLike,
    isWhitelisted: boolean,
    tokenMetadata: IBridge.TokenMetadataStruct
  ];
  export type OutputTuple = [
    tokenKey: string,
    wrappedToken: string,
    isWhitelisted: boolean,
    tokenMetadata: IBridge.TokenMetadataStructOutput
  ];
  export interface OutputObject {
    tokenKey: string;
    wrappedToken: string;
    isWhitelisted: boolean;
    tokenMetadata: IBridge.TokenMetadataStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRequestExecutedEvent {
  export type InputTuple = [nonce: BigNumberish, srcChainId: BigNumberish];
  export type OutputTuple = [nonce: bigint, srcChainId: bigint];
  export interface OutputObject {
    nonce: bigint;
    srcChainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRequestedEvent {
  export type InputTuple = [request: IBridge.TransferRequestStruct];
  export type OutputTuple = [request: IBridge.TransferRequestStructOutput];
  export interface OutputObject {
    request: IBridge.TransferRequestStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IBridge extends BaseContract {
  connect(runner?: ContractRunner | null): IBridge;
  waitForDeployment(): Promise<this>;

  interface: IBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeTransferRequests: TypedContractMethod<
    [batch: IBridge.TransferExecutionDetailsStruct[]],
    [void],
    "nonpayable"
  >;

  getAdmin: TypedContractMethod<[], [string], "view">;

  getAuthority: TypedContractMethod<[], [string], "view">;

  requestTransfer: TypedContractMethod<
    [
      tokenKey: BytesLike,
      to: AddressLike,
      amount: BigNumberish,
      destinationChainId: BigNumberish
    ],
    [void],
    "payable"
  >;

  setStakingManager: TypedContractMethod<
    [stakingManager: AddressLike],
    [void],
    "nonpayable"
  >;

  updateWhitelistStatus: TypedContractMethod<
    [tokenKey: BytesLike, enabled: boolean, tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  whitelistToken: TypedContractMethod<
    [
      tokenKey: BytesLike,
      enabled: boolean,
      tokenAddress: AddressLike,
      tokenSymbol: string,
      tokenName: string,
      tokenDecimals: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeTransferRequests"
  ): TypedContractMethod<
    [batch: IBridge.TransferExecutionDetailsStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAuthority"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestTransfer"
  ): TypedContractMethod<
    [
      tokenKey: BytesLike,
      to: AddressLike,
      amount: BigNumberish,
      destinationChainId: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setStakingManager"
  ): TypedContractMethod<[stakingManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateWhitelistStatus"
  ): TypedContractMethod<
    [tokenKey: BytesLike, enabled: boolean, tokenAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "whitelistToken"
  ): TypedContractMethod<
    [
      tokenKey: BytesLike,
      enabled: boolean,
      tokenAddress: AddressLike,
      tokenSymbol: string,
      tokenName: string,
      tokenDecimals: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "NewTokenWhitelisted"
  ): TypedContractEvent<
    NewTokenWhitelistedEvent.InputTuple,
    NewTokenWhitelistedEvent.OutputTuple,
    NewTokenWhitelistedEvent.OutputObject
  >;
  getEvent(
    key: "TokenWhitelistStatusUpdated"
  ): TypedContractEvent<
    TokenWhitelistStatusUpdatedEvent.InputTuple,
    TokenWhitelistStatusUpdatedEvent.OutputTuple,
    TokenWhitelistStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenWrapped"
  ): TypedContractEvent<
    TokenWrappedEvent.InputTuple,
    TokenWrappedEvent.OutputTuple,
    TokenWrappedEvent.OutputObject
  >;
  getEvent(
    key: "TransferRequestExecuted"
  ): TypedContractEvent<
    TransferRequestExecutedEvent.InputTuple,
    TransferRequestExecutedEvent.OutputTuple,
    TransferRequestExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TransferRequested"
  ): TypedContractEvent<
    TransferRequestedEvent.InputTuple,
    TransferRequestedEvent.OutputTuple,
    TransferRequestedEvent.OutputObject
  >;

  filters: {
    "NewTokenWhitelisted(bytes32,tuple,tuple)": TypedContractEvent<
      NewTokenWhitelistedEvent.InputTuple,
      NewTokenWhitelistedEvent.OutputTuple,
      NewTokenWhitelistedEvent.OutputObject
    >;
    NewTokenWhitelisted: TypedContractEvent<
      NewTokenWhitelistedEvent.InputTuple,
      NewTokenWhitelistedEvent.OutputTuple,
      NewTokenWhitelistedEvent.OutputObject
    >;

    "TokenWhitelistStatusUpdated(bytes32,tuple)": TypedContractEvent<
      TokenWhitelistStatusUpdatedEvent.InputTuple,
      TokenWhitelistStatusUpdatedEvent.OutputTuple,
      TokenWhitelistStatusUpdatedEvent.OutputObject
    >;
    TokenWhitelistStatusUpdated: TypedContractEvent<
      TokenWhitelistStatusUpdatedEvent.InputTuple,
      TokenWhitelistStatusUpdatedEvent.OutputTuple,
      TokenWhitelistStatusUpdatedEvent.OutputObject
    >;

    "TokenWrapped(bytes32,address,bool,tuple)": TypedContractEvent<
      TokenWrappedEvent.InputTuple,
      TokenWrappedEvent.OutputTuple,
      TokenWrappedEvent.OutputObject
    >;
    TokenWrapped: TypedContractEvent<
      TokenWrappedEvent.InputTuple,
      TokenWrappedEvent.OutputTuple,
      TokenWrappedEvent.OutputObject
    >;

    "TransferRequestExecuted(uint256,uint64)": TypedContractEvent<
      TransferRequestExecutedEvent.InputTuple,
      TransferRequestExecutedEvent.OutputTuple,
      TransferRequestExecutedEvent.OutputObject
    >;
    TransferRequestExecuted: TypedContractEvent<
      TransferRequestExecutedEvent.InputTuple,
      TransferRequestExecutedEvent.OutputTuple,
      TransferRequestExecutedEvent.OutputObject
    >;

    "TransferRequested(tuple)": TypedContractEvent<
      TransferRequestedEvent.InputTuple,
      TransferRequestedEvent.OutputTuple,
      TransferRequestedEvent.OutputObject
    >;
    TransferRequested: TypedContractEvent<
      TransferRequestedEvent.InputTuple,
      TransferRequestedEvent.OutputTuple,
      TransferRequestedEvent.OutputObject
    >;
  };
}
