/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iStakingSol from "./IStaking.sol";
export type { iStakingSol };
export type { IBridge } from "./IBridge";
export type { IERC20Mintable } from "./IERC20Mintable";
export type { IOwnablePausable } from "./IOwnablePausable";
export type { IStakeManager } from "./IStakeManager";
