ethereum:
  name: "Ethereum"
  # rpc_endpoint: "https://sepolia.gateway.tenderly.co"
  rpc_endpoint: "http://localhost:8545"
  address: "0x71C95911E9a5D330f4D621842EC243EE1343292e"
  chain_id: 1
  block_confirmations: 0
  block_production_time: 6s
  start_block: 0

subtensor:
  name: "Subtensor"
  chain_id: 945
  rpc_endpoint: "http://localhost:9944"
  # rpc_endpoint: "https://evm-testnet.dev.opentensor.ai"
  address: "0x71C95911E9a5D330f4D621842EC243EE1343292e"
  block_confirmations: 0
  block_production_time: 6s
  start_block: 0

