ethereum:
  name: "Ethereum"
  # rpc_endpoint: "https://sepolia.gateway.tenderly.co"
  rpc_endpoint: "http://host.docker.internal:8545"
  address: "0x71C95911E9a5D330f4D621842EC243EE1343292e"
  chain_id: 1
  block_confirmations: 0
  block_production_time: 6s
  start_block: 0

subtensor:
  name: "Subtensor"
  chain_id: 0
  rpc_endpoint: "http://host.docker.internal:9944"
  # rpc_endpoint: "https://evm-testnet.dev.opentensor.ai"
  address: "0x057ef64E23666F000b34aE31332854aCBd1c8544"
  block_confirmations: 0
  block_production_time: 6s
  start_block: 0

