[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-foundry-upgrades/=node_modules/openzeppelin-foundry-upgrades/src/",
    "@openzeppelin/contracts/=node_modules/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=node_modules/openzeppelin-contracts-upgradeable/contracts/",
]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.22"
build_info = true
extra_output = ["storageLayout"]
ffi = true
ast = true
