/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as stakePrecompileSol from "./StakePrecompile.sol";
export type { stakePrecompileSol };
